name: Generate & Deploy Docs

on:
  push:
    branches: [main, master]
    paths:
      - "lib/**"
      - "pubspec.yaml"
      - ".github/workflows/docs_deploy.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.1
      
      - name: Disable Flutter analytics
        run: flutter config --no-analytics
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Install dartdoc
        run: flutter pub global activate dartdoc
      
      - name: Generate documentation
        run: |
          export PATH="$PATH:$HOME/.pub-cache/bin"
          mkdir -p docs
          dartdoc --output docs
          
          # Debug - List what was generated
          echo "Files generated in docs directory:"
          ls -la docs
      
      - name: Create correct structure for GitHub Pages
        run: |
          # Si dartdoc generó 'docs/api', copia su contenido a 'docs'
          if [ -d "docs/api" ]; then
            echo "Moving docs/api/* to docs/"
            cp -r docs/api/* docs/
            rm -rf docs/api
          fi
          
          # En caso de que dartdoc genere en otro directorio, ajustamos según sea necesario
          if [ ! -f "docs/index.html" ]; then
            echo "Creating custom index.html"
            cat > docs/index.html << EOF
            <!DOCTYPE html>
            <html>
              <head>
                <meta charset="UTF-8">
                <title>Matrix API Documentation</title>
              </head>
              <body>
                <h1>Matrix API Documentation</h1>
                <p>Welcome to the API documentation for the Matrix project.</p>
                <ul>
                  <li><a href="./classes.html">Classes</a></li>
                  <li><a href="./functions.html">Functions</a></li>
                </ul>
              </body>
            </html>
            EOF
          fi
          
          # Debug - Verificar estructura final
          echo "Final documentation structure:"
          find docs -type f | sort
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4