name: Generate & Deploy Docs

on:
  push:
    branches: [main, master]
    paths:
      - "lib/**"
      - "pubspec.yaml"
      - ".github/workflows/docs_deploy.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.1
      
      - name: Disable Flutter analytics
        run: flutter config --no-analytics
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Install dartdoc
        run: flutter pub global activate dartdoc
      
      - name: Generate documentation
        run: |
          export PATH="$PATH:$HOME/.pub-cache/bin"
          mkdir -p docs
          dartdoc --output docs
          
          # Debug - List what was generated
          echo "Files generated in docs directory:"
          ls -la docs
      